#!/bin/bash
echo Dont forget quotes around both parameters
if [ $1 == "-h" ]; then
    echo "Arg 1 is search value, arg 2 is file (*.ext)"
    exit
fi
find . -name "$2" -not -path "**/node_modules/*" -exec  grep -i -H -n "$1" {} \;
